Update Connect wallet
Ao-Collaboration/paperhands-web pull request #6
Opened 2022-08-03 00:21 UTC by foopod

2022-08-03 20:30 UTC, ScreamingHawk requested changes
I'm going to ignore this PR for now and focus on the after wallet connect functionality. Definitely needs more work before it's in a usable state

2022-08-03 20:30 UTC, ScreamingHawk commented on src/pages/Mint/Mint.tsx
> +				<Header />
Remove `hasHeader{false}` instead

2022-08-03 20:30 UTC, ScreamingHawk commented on src/pages/ConnectWallet/ConnectWallet.tsx
> +			</div>
Idk if this should be part of the connect wallet section

2022-08-03 20:30 UTC, ScreamingHawk commented on src/pages/ConnectWallet/ConnectWallet.tsx
> +			<Footer />
Remove `hasFooter={false}` instead

2022-08-03 20:31 UTC, ScreamingHawk commented on src/pages/ConnectWallet/ConnectWallet.tsx
> +			</div>
Maybe keep it but replace the button with the `ConnectWallet` button

2022-08-03 20:31 UTC, ScreamingHawk commented on src/pages/ConnectWallet/ConnectWallet.tsx
> +			</div>
Would be nice if this primary section is it's own shared component across both `Home` and here

2022-08-03 22:35 UTC, ScreamingHawk commented
After doing #7 I think we can drop this. The design is a bit different to the wireframe. What do you think?

2022-08-06 23:17 UTC, foopod commented
Closing as not merging, see above comments.

2022-08-06 23:17 UTC, closed without merging